# Generated by Django 5.0.1 on 2024-03-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_producto_delete_productosellado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='fproducto',
        ),
    ]
