# Generated by Django 5.0.1 on 2024-03-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_alter_singles_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singles',
            name='foto',
        ),
    ]
