# Generated by Django 5.0.1 on 2024-03-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0018_alter_producto_fproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fproducto',
            field=models.ImageField(default='', upload_to='media/avatares'),
        ),
    ]
