# Generated by Django 5.0.1 on 2024-03-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0020_alter_producto_fproducto_alter_singles_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singles',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
