# Generated by Django 5.0.1 on 2024-03-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosellado',
            name='producto',
            field=models.ImageField(default='../media/avatares/1.jpeg', upload_to='media/avatares'),
        ),
    ]
