# Generated by Django 5.0.1 on 2024-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_singles_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('producto', models.ImageField(default='', upload_to='media/avatares')),
            ],
        ),
        migrations.DeleteModel(
            name='Productosellado',
        ),
    ]
