# Generated by Django 5.0.1 on 2024-03-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0015_alter_producto_fproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ofertas',
            new_name='Oferta',
        ),
    ]
