# Generated by Django 5.0.1 on 2024-03-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0016_rename_ofertas_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dni',
            new_name='telefono',
        ),
    ]
