# Generated by Django 5.0.1 on 2024-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0021_alter_singles_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singles',
            name='foto',
            field=models.ImageField(default='../media/avatares/1.jpeg', upload_to='avatares'),
        ),
    ]
