# Generated by Django 5.0.1 on 2024-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0023_alter_singles_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fproducto',
            field=models.ImageField(default='media/avatares', upload_to='media/avatares'),
        ),
    ]
