# Generated by Django 5.0.1 on 2024-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0028_alter_singles_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singles',
            name='foto',
            field=models.ImageField(upload_to='', verbose_name='media'),
        ),
    ]
