# Generated by Django 5.0.1 on 2024-03-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0029_alter_singles_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singles',
            name='foto',
            field=models.ImageField(default='avatares/default_1.jpeg', upload_to='avatares'),
        ),
    ]
