# Generated by Django 5.0.1 on 2024-03-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0030_alter_singles_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fproducto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
