# Generated by Django 5.0.1 on 2024-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0036_alter_producto_fproducto_alter_singles_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fproducto',
            field=models.ImageField(blank=True, upload_to='media/avatares'),
        ),
    ]
