# Generated by Django 5.0.1 on 2024-03-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0038_alter_producto_fproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fproducto',
            field=models.ImageField(default='../media/avatares/default_1.jpeg', upload_to='media/avatares'),
        ),
    ]
