# Generated by Django 5.0.1 on 2024-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0041_remove_producto_fproducto_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
